### ISSUE TITLE
Wording vor nächstem Release

### ISSUE THREAD

**Issue by HonMed** [Blaulichtplaner/blaulichtplaner-app#90]
Benachrichtigung Einstellungen 3 Änderungen:

"Benachrichtigung via Smartphone"

"E-Mail Benachrichtigungen"
"Benachrichtigung via E-Mail"

Filter Bewerbungen:

"Dienste mit Bewerbung" zu "Beworbene Dienste"

(siehe auch issue Webapp)

**Comment by grundid** [comment]
Dienstpäne Tab korrigieren
